import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface": "#131313",
        "apple-silver": "#8E8E93",
        "secondary-fixed-dim": "#c8c6c8",
        "surface-container-low": "#1b1b1b",
        "on-surface": "#e2e2e2",
        "inverse-surface": "#e2e2e2",
        "tertiary-fixed": "#ffe088",
        "on-primary-container": "#636565",
        "tertiary-container": "#ffe088",
        "surface-container-high": "#2a2a2a",
        "on-secondary": "#303032",
        "primary-fixed": "#e2e2e2",
        "on-tertiary-container": "#7b6100",
        "primary": "#ffffff",
        "surface-container-highest": "#353535",
        "tertiary-fixed-dim": "#e9c349",
        "success-green": "#34C759",
        "surface-variant": "#353535",
        "on-primary": "#2f3131",
        "secondary": "#c8c6c8",
        "on-secondary-container": "#b6b4b7",
        "surface-dim": "#131313",
        "warning-amber": "#FF9F0A",
        "danger-red": "#FF3B30",
        "on-tertiary-fixed": "#241a00",
        "surface-bright": "#393939",
        "on-primary-fixed-variant": "#454747",
        "on-background": "#e2e2e2",
        "outline-variant": "#444748",
        "on-tertiary": "#3c2f00",
        "on-primary-fixed": "#1a1c1c",
        "primary-container": "#e2e2e2",
        "on-error-container": "#ffdad6",
        "surface-container-lowest": "#0e0e0e",
        "inverse-primary": "#5d5f5f",
        "on-tertiary-fixed-variant": "#574500",
        "error-container": "#93000a",
        "surface-charcoal": "#1C1C1E",
        "on-error": "#690005",
        "surface-tint": "#c6c6c7",
        "secondary-container": "#474649",
        "primary-fixed-dim": "#c6c6c7",
        "inverse-on-surface": "#303030",
        "tertiary": "#ffffff",
        "background": "#131313",
        "surface-container": "#1f1f1f",
        "on-surface-variant": "#c4c7c8",
        "secondary-fixed": "#e4e2e4",
        "on-secondary-fixed-variant": "#474649",
        "apple-gold": "#E6B800",
        "on-secondary-fixed": "#1b1b1d",
        "outline": "#8e9192",
        "error": "#ffb4ab",
      },
      spacing: {
        "card-padding": "24px",
        "gutter": "16px",
        "margin-desktop": "48px",
        "margin-mobile": "16px",
        "unit": "4px",
      },
    },
  },
  plugins: [],
};

export default config;
